"""Initial database schema

Revision ID: 86e8d5508b84
Revises: 
Create Date: 2025-09-17 22:42:12.945869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86e8d5508b84'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_requirements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('requirements_text', sa.Text(), nullable=False),
    sa.Column('schema_mappings', sa.JSON(), nullable=True),
    sa.Column('upload_date', sa.DateTime(), nullable=False),
    sa.Column('processed_requirements', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=False),
    sa.Column('document_type', sa.Enum('PDF', 'DOCX', 'TXT', name='documenttype'), nullable=False),
    sa.Column('schema_type', sa.Enum('EU_ESRS_CSRD', 'UK_SRD', name='schematype'), nullable=True),
    sa.Column('processing_status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='processingstatus'), nullable=False),
    sa.Column('document_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rag_responses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('source_chunks', sa.JSON(), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('generation_timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schema_elements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('schema_type', sa.Enum('EU_ESRS_CSRD', 'UK_SRD', name='schematype'), nullable=False),
    sa.Column('element_code', sa.String(length=50), nullable=False),
    sa.Column('element_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_element_id', sa.String(), nullable=True),
    sa.Column('requirements', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_element_id'], ['schema_elements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('text_chunks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('embedding_vector', sa.JSON(), nullable=True),
    sa.Column('schema_elements', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('text_chunks')
    op.drop_table('schema_elements')
    op.drop_table('rag_responses')
    op.drop_table('documents')
    op.drop_table('client_requirements')
    # ### end Alembic commands ###
