# Alert rules for CSRD RAG System

groups:
  - name: csrd_system_alerts
    rules:
      # High CPU usage
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100) > 80
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is above 80% for more than 2 minutes on {{ $labels.instance }}"

      # High memory usage
      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 85
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage detected"
          description: "Memory usage is above 85% for more than 2 minutes on {{ $labels.instance }}"

      # Low disk space
      - alert: LowDiskSpace
        expr: (node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"}) * 100 < 10
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Low disk space"
          description: "Disk space is below 10% on {{ $labels.instance }}"

      # Application down
      - alert: ApplicationDown
        expr: up{job="csrd-app"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "CSRD RAG Application is down"
          description: "The CSRD RAG application has been down for more than 1 minute"

      # Database connection issues
      - alert: DatabaseConnectionIssues
        expr: increase(database_connection_errors_total[5m]) > 5
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Database connection issues"
          description: "More than 5 database connection errors in the last 5 minutes"

      # High error rate
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) * 100 > 5
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High error rate"
          description: "Error rate is above 5% for more than 2 minutes"

      # Slow response times
      - alert: SlowResponseTimes
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2
        for: 3m
        labels:
          severity: warning
        annotations:
          summary: "Slow response times"
          description: "95th percentile response time is above 2 seconds for more than 3 minutes"

  - name: csrd_business_alerts
    rules:
      # Document processing failures
      - alert: DocumentProcessingFailures
        expr: increase(document_processing_failures_total[10m]) > 3
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Document processing failures"
          description: "More than 3 document processing failures in the last 10 minutes"

      # RAG query failures
      - alert: RAGQueryFailures
        expr: increase(rag_query_failures_total[10m]) > 5
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "RAG query failures"
          description: "More than 5 RAG query failures in the last 10 minutes"

      # Vector database issues
      - alert: VectorDatabaseDown
        expr: vector_db_health_status != 1
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Vector database is down"
          description: "Vector database health check is failing"

      # Celery worker issues
      - alert: CeleryWorkerDown
        expr: celery_active_workers == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "No Celery workers available"
          description: "All Celery workers are down or not responding"

      # Queue backlog
      - alert: HighQueueBacklog
        expr: celery_queue_length > 100
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High queue backlog"
          description: "Celery queue has more than 100 pending tasks for more than 5 minutes"